"""empty message

Revision ID: ff4c6af4f0ce
Revises: 98e13762e5b3
Create Date: 2024-02-02 04:47:31.916194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff4c6af4f0ce'
down_revision = '98e13762e5b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
